
# Name of your workflow.
name: "Integration tests"
on: [push, workflow_dispatch]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: windows
          - os: ubuntu-latest
            platform: ubuntu
          - os: macos-latest
            platform: macos

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    # Sets up a flutter environment.
      # https://github.com/marketplace/actions/flutter-action
    - uses: subosito/flutter-action@v1
      with:
        channel: "stable" # or: 'dev' or 'beta'
    - name: Pub get
      run: flutter pub get
      working-directory: example
      
    - name: Run Integration Tests on macOS
      working-directory: example
      if: matrix.platform == 'macos'
      run: flutter -d macOS test integration_test

    - name: Run Integration Tests on Windows
      working-directory: example
      if: matrix.platform == 'windows'
      run: flutter test -d windows integration_test

    - name: Run Integration Tests on Ubuntu
      working-directory: example
      if: matrix.platform == 'ubuntu'
      run: flutter test -d Linux integration_test